### ISSUE TITLE
old version of abseil causes error during installation

### ISSUE THREAD

**Issue by estnml** [versatica/mediasoup#1080]
### Your environment

- Operating system: archlinux 6.3.1-arch1-1 (64-bit)
- Node version: v19.9.0
- npm version: 8.19.2
- gcc/clang version: gcc version 13.1.1 20230429 (GCC)
- mediasoup version: 3.11.24
- mediasoup-client version: 3.6.84

### Issue description

When i try to install mediasoup with "npm i mediasoup" i get the following error.
Error log: 
[2023-05-13T09_25_32_203Z-debug-0.log](https://github.com/versatica/mediasoup/files/11469860/2023-05-13T09_25_32_203Z-debug-0.log)

I asked for help in the mediasoup forum https://mediasoup.discourse.group/t/need-help-installing-mediasoup/5222 and im told the problem is "Since mediasoup does not compile with gcc-13, because it uses outdated version of abseil, it’s the problem of mediasoup"

i can install mediasoup-client package without any problem. Bu cant install the mediasoup

**Comment by ibc** [comment]
Those are the available `abseil-cpp` versions in https://mesonbuild.com/Wrapdb-projects.html:

<img width="376" alt="CleanShot-2023-05-16-at-17 53 42@2x" src="https://github.com/versatica/mediasoup/assets/16191/ce28f943-ef46-41a4-821e-d87b635b60e2">

We cannot use the latest [20230125.1-1](https://wrapdb.mesonbuild.com/v2/abseil-cpp_20230125.1-1/abseil-cpp.wrap) because it requires C++14 and we don't want to require it yet, or may be we should?

Anyway, do we know in which version of `abseil-cpp` the issue that prevents it from compiling in gcc-13 was fixed? According to the [fixing commit](https://github.com/abseil/abseil-cpp/commit/36a4b073f1e7e02ed7d1ac140767e36f82f09b7c) it's included in all versions since 2022, am I right?

**Comment by nazar-pc** [comment]
We discussed it a few times in the past and I have not seen anyone objecting against bumping requirement to C++14. I'd even go with C++17 to be honest, it is already 5+ years old and compiler support started even before that.

**Comment by ibc** [comment]
Right. Let me first update to C++14.

**Comment by ibc** [comment]
It should be enough by changing it here, right?

```diff
diff --git a/worker/meson.build b/worker/meson.build
index 4be31c0c0..72f38f1b9 100644
--- a/worker/meson.build
+++ b/worker/meson.build
@@ -3,7 +3,7 @@ project(
   ['c', 'cpp'],
   default_options : [
     'warning_level=1',
-    'cpp_std=c++11',
+    'cpp_std=c++14',
     'default_library=static',
   ],
   meson_version: '>= 0.58',
```

**Comment by nazar-pc** [comment]
Should be code-wise + docs in various places, including website.

**Comment by nazar-pc** [comment]
Could bump Meson version too actually.

**Comment by ibc** [comment]
I'll check in website later and not sure which Meson version to set (I prefer to separate that task).

**Comment by ibc** [comment]
Ok, C++14 works fine. So let's update to C++17 XD

@nazar-pc which version of Meson should I set in `meson.build`?

**Comment by ibc** [comment]
Let's move the topic to the PR: https://github.com/versatica/mediasoup/pull/1081
