### ISSUE TITLE
[flatbuffers] flatc build system is not reliable enough

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1154]
- `make flatc` doesn't recompile existing `.fbs` files, so `make flatc-force` is needed every time a change is done in any `.rfb.  file.
- If some FBS `table` is renamed, the `FBS` folder keeps the old one forever (a folder with the old name) and it may produce build errors if it references a type/name that no longer exists, so manual delete or `make flatc-force` is needed.

IMHO this is too weak and error prune.

**Comment by nazar-pc** [comment]
In case of Rust version flatbufferes will be built by build script of `mediasoup-sys`, which will ensure compiled results are always up to date. It has ability to track file changes to avoid recompilation when files not change, so this will be TypeScript-specific.

**Comment by jmillan** [comment]
I've tried to create a Meson `custom_target` in order to build the C++ flatbuffers headers as part of the build process, which I expect would correctly do it just when the schemas change. I've already spent some time today without success. 

NOTE: I'll continue in this direction. I'll investigate it later.

**Comment by ibc** [comment]
Is there anything I could try here? And perhaps @nazar-pc?

**Comment by nazar-pc** [comment]
What is the problem with recompining it every time though? I'll take care of the Rust side BTW.

**Comment by jmillan** [comment]
> Is there anything I could try here? And perhaps @nazar-pc?

I'm trying to use meson [custom_target](https://mesonbuild.com/Generating-sources.html) to generate the flatbuffers header files out of the schemas. I've found an [issue I've already reported](https://github.com/mesonbuild/meson/issues/12354).

I think this is the best way we can generate the headers, once it only generates them when the schemas change.

> What is the problem with recompining it every time though?

That every change in a single .cpp file will incur in re-generating the flatbuffers header files and due to that, by the time of writing this,  141 .cpp files need to be recompiled.

> I'll take care of the Rust side BTW.

:+1:
