### ISSUE TITLE
Firefox DTLS certificate error for second RTCPeerConnection on page

### ISSUE THREAD

**Issue by kolychev** [versatica/mediasoup#127]
We are building app that creates multiple PeerConnections to mediasoup server on same page.
The Scheme works ok with chrome / latest safari, but firefox sometimes drops peer connection on DTLS exchange stage. 

Issue happens at least with Firefox v54 and v55 (latest).

After turning logs in firefox I see following issue logged: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

This happens SOMETIMES but quite often in case mediasoup generate DTSL keys automatically.

If I generate DTLS keys manually and pass it with dtlsCertificateFile/dtlsPrivateKeyFile options on start of mediasoup, this issue does not happen.

Not sure if it is related to some mediasoup issue or it is on firefox side, but at least the workaround with pre-generated certificates might help someone.

**Comment by ibc** [comment]
Interesting. I don't see the difference. Even if you pass your own DTLS certificates to mediasoup, the certificate issuer and serial will always be the same.

Also, I don't understand why Firefox should complain about that. If you connect to the same remote DTLS endpoint it may perfectly happen that it uses the same certificate, what to expect otherwise?

**Comment by ibc** [comment]
Currently, in mediasoup v2 (to be released very soon) we typically open 2 peerconnections in client side (one for sending and one for receiving), and I've never seen this problem.

Anyhow, I always use DTLS certificate files (rather than letting mediasoup generate them). Will test that soon.

**Comment by nils-ohlmeier** [comment]
Interesting. @kolychev do you know if the automatically generated certs use the same algorithms as your manually created ones, e.g. RSA vs. eliptic curve, different hash functions etc?

**Comment by kolychev** [comment]
I am not sure what algorithms are used for auto-generated certs in mediasoup, but here is how I generate it manually to make Firefox work, I hope it will help:

openssl req -new -x509 -nodes -days 365 -newkey rsa:2048 -sha256 -subj '/CN=/O=/C=/' -keyout dtls.key -out dtls.crt

**Comment by nils-ohlmeier** [comment]
The obvious difference I can see is that mediasoup's code creates a 1024 bit key, where @kolychev command generates a 2048 bit key. Not sure why that would matter. But might be worth a try to see what happens with a manually created 1024 bit key file read in by mediasoup.

**Comment by kolychev** [comment]
I think I have narrowed this issue. It is related to number of workers used. When there is only one worker used, it does not matter what certificate used. But if there are several workers, in case of manually set certificate, all workers use same cert, but for auto-generated - they use different certificates and the issue happens sometimes. The more workers you have, the more often issue happens.

**Comment by ibc** [comment]
Good catch @kolychev!

Yep, the browser should not make assumptions regarding DTLS certificates no matter the URL origin.

**Comment by jmillan** [comment]
Firefox rejects a certificate when this contains the same serial number as another certificate issued by the certificate authority.

There is a related [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=435013) which has been around for `10 years`.

Having said this. I'd recommend you @kolychev to use your own certificates if you are using multiple  mediasoup workers.

I think this issue can be safely closed, since it's not an issue in mediasoup.

**Comment by kolychev** [comment]
Sure no problem lets close it if you feel this should be fixed on Firefox side.
I have opened it to let people know about workaround while Firefox guys not fix it.

**Comment by ibc** [comment]
Let's reopen this. We may just generate random SN to avoid this problem.

**Comment by ibc** [comment]
> Firefox rejects a certificate when this contains the same serial number as another certificate issued by the certificate authority.

@jmillan we create a random serial number within `DtlsTransport`:

```c++
ASN1_INTEGER_set(
  X509_get_serialNumber(DtlsTransport::certificate),
  static_cast<uint64_t>(Utils::Crypto::GetRandomUInt(1000000, 9999999)));
```

so I don't fully understand where the issue is.

**Comment by jmillan** [comment]
That's certainly true. Serial number is randomly created.

I was just pointing to the firefox documentation regarding the error reported by @kolychev.

Interestingly, I've come up with a [script](https://github.com/mozilla/betachannel/blob/547ae913ea9aec3876844432c6739c1dde746447/server/bin/generate_cert.sh) in mozilla github repo witch comments the following:

````
# XXX: We cannot give the trusted and untrusted versions of the certs the same
# subject names because otherwise we'll run into
# SEC_ERROR_REUSED_ISSUER_AND_SERIAL.
org="O=Examplla Corporation,L=Mountain View,ST=CA,C=US"
ca_subj="CN=Examplla Root CA,OU=Examplla CA,$org"
ee_subj="CN=Examplla Marketplace App Signing,OU=Examplla Marketplace App Signing,$org"
````

Ouchh..

And we are setting the certificate subject the value of `mediasoup`.

**Comment by ibc** [comment]
@kolychev if you are using mediasoup 'v2' branch, may you update and try again? 3dff71d2077b9b6737ea8ae4ef476228fe09fd77 makes the auto-generated certificate's subject random.

**Comment by kolychev** [comment]
Unfortunately I am still on v1, once we migrate our code to v2, I will give it a try.

**Comment by jnoring** [comment]
I wanted to leave a comment here, because I just finished troubleshooting this with licode (which has very similar DTLS code).  For us, an update from 14.04 to 16.04 caused this defect.

The basic problem is: Firefox doesn't like it when there are certs in use with identical serials and issuers, but the underlying cert is different.  Which makes sense: for a given certificate, the serial, issuer and underlying cert should all remain consistent.

The bug in licode was: bad use of `rand()`.  On 14.04, something was seeding rand correctly, which lead to different serial numbers on the underlying certificate.  On 16.04, nothing was seeding rand, and 1 to many processes would all end up with certs where the serial was the same, the issuer was the same, but the underlying cert was slightly different.

I think the best way to mitigate this in software like licode and mediasoup is: use a single certificate for all processes (the certificate can be generated when the app starts, but the basic idea is all workers _should_ use the same certificate).  This avoids a ton of issues with self-signed certificates colliding with one another in strange ways.

**Comment by ibc** [comment]
mediasoup uses a single DTLS certificate (given by the app or auto-generated when started) for all DTLS connections.

**Comment by jnoring** [comment]
if you auto-generate, doesn't each worker auto-generate its own certificate?  

That's where licode gets itself in hot water with odd cert collisions: each worker process they have generates its own certificate when it first starts.

**Comment by ibc** [comment]
Right, each worker generates its own cert (unless all the workers are provided with the same cert via setting).

**Comment by jnoring** [comment]
That isn't a "single DTLS certificate" then.  Mediasoup uses multiple certificates if you auto-generate because each worker has a different certificate.

If auto-generation code is written correctly (and I believe it is in media soup--there's sufficient "randomness" in cert generation), this should be fine.  I think architecturally it makes the most sense to pass in a cert instead of auto-generating in code.

Also, thanks a ton for the work you've done in your DtlsTransport.  It's way better code than what's in licode.

**Comment by ibc** [comment]
Nice to know that, thanks :)
