### ISSUE TITLE
Rust docs for 0.13 failed to build

### ISSUE THREAD

**Issue by PaulOlteanu** [versatica/mediasoup#1270]
### Issue description
[The docs](https://docs.rs/crate/mediasoup/latest) for release 0.13 of mediasoup for rust failed to build. [Here's](https://docs.rs/crate/mediasoup/0.13.0/builds/1036978) a direct link to the error.

I can't really try and help more in depth at the moment, but I do know you can try building docs locally to test the build https://github.com/rust-lang/docs.rs#build-subcommand.

**Comment by nazar-pc** [comment]
The reason is that we skip the whole build script for build.rs: https://github.com/versatica/mediasoup/blob/f9c081c41e90a84d837d2a26b700d1fee84430c4/worker/build.rs#L5-L8

Now that we have flatbuffers (that we thankfully compile with Rust code) we need to move that check below flatbuffers compilation.

@PaulOlteanu would you mind sending a PR to fix this, please?

**Comment by ibc** [comment]
To here? https://github.com/versatica/mediasoup/blob/f9c081c41e90a84d837d2a26b700d1fee84430c4/worker/build.rs#L47

**Comment by nazar-pc** [comment]
Exactly, just move the check there and it should succeed.

**Comment by ibc** [comment]
https://github.com/versatica/mediasoup/pull/1271
