### ISSUE TITLE
Why this does not work on windows ?

### ISSUE THREAD

**Issue by Zaid-Al-Omari** [versatica/mediasoup#172]
May i know the reason of why this does not work on windows?

I could spend some time porting this lib to windows.

**Comment by ibc** [comment]
I would appreciate that you used the mailing list for this kind of questions and leave GitHub issues for just bug reporting :)

mediasoup does not work in Windows because we don't use Windows. The C++ part of mediasoup uses libraries that work both in *nix and Windows (libuv, openssl, libsrtp, libjsoncpp, etc), but also uses some C++ stuff not available in Windows environments (some includes, etc). I don't think it would be a very heavy work. In fact, I've seen some forks of mediasoup with some work on this.

If you make it work on Windows and provide a PR, that would be nice :)

**Comment by Zaid-Al-Omari** [comment]
Thanks a lot for your input, and excuse me for posting this twice, as I didn't get a notification about the first one,

**Comment by lalakis1** [comment]
Can you please point out to mediasoup windows fork? I couldn't find any.
Thanks

**Comment by Globik** [comment]
@lalakis1 on windows this stuff does not work cuz it's using heavy UnixStreamSocket under the hood. The messages from mediasoup c++ does not reach node.js server, hanging out.
As a workaround could be callbacks written native on c or c plusplus but then say to node.js good bye in this case.

**Comment by sellis1234** [comment]
Does ti work on windows yet?

**Comment by ibc** [comment]
It does
