### ISSUE TITLE
H264 keyframe not handled or not routed

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#313]
As explained in https://mediasoup.discourse.group/t/h264-openh264-externalencoder-in-chrome/85, if H264 codec is used with `'packetization-mode': 1, 'profile-level-id': '42001f'`, the remote consumer does not receive any RTP packet, **even without using simulcast**.

This is terrible.

**Comment by ibc** [comment]
The problem is that we do not detect key frames in H264 with this media codec in the Router:

```js
{
	kind       : 'video',
	mimeType   : 'video/h264',
	clockRate  : 90000,
	parameters :
	{
		'packetization-mode'      : 1,
		'profile-level-id'        : '42001f',
		'level-asymmetry-allowed' : 1
	}
}
```

It may be related to the use of frame marking extension, no idea.

BTW remember that, with the above H264 settings, Chrome does **NOT** produce simulcast but a single stream.

**Comment by ibc** [comment]
Ok, the problem is that, when H264 ExternalEncoder is used, Chrome:

* Ignores simulcast (it just sends a single stream).
* It adds frame-marking to the packets, but it never sets bit "i" (independent) to 1, which is needed for key frame detection.

Issue reported in libwebrtc: https://bugs.chromium.org/p/webrtc/issues/detail?id=10746

**Comment by ibc** [comment]
Let's keep this issue open until libwebrtc guys fix the issue.

**Comment by dominikzane** [comment]
Thank you — is there any way/workaround to still use ExternalEncoder (without simulcast) in mediasoup v2 in the meantime even with the limitations, until this is fixed?

**Comment by jmillan** [comment]
@dominikbalogh,

mediasoup v2 does not implement the RTP Frame Marking header extension, so this specific issue does not apply to v2.

As indicated in the [mediasoup.discourse.group](https://mediasoup.discourse.group/t/h264-openh264-externalencoder-in-chrome/85), in order to enable the external H246 encoder you must define a single video router codec with the indicated `packetization-mode` and `profile-level-id`:

```
'packetization-mode': 1, 'profile-level-id': '42001f'
```

**Comment by dominikzane** [comment]
Sorry, maybe we are missing something, but how exactly do we restrict the codecs to a single codec (as you are describing), instead of all the available codecs in the mediasoup-client? It does not seem to work.

(This is very important for us to make it work immediately because the HW encoder quite significantly impacts CPU and thus battery life)

**Comment by jmillan** [comment]
@dominikbalogh, please start a discussion in https://mediasoup.discourse.group/ since your question is out of the scope of this issue.

In order to force a video codec in mediasoup (v2) just provide that single video codec description when creating the [server Room](https://mediasoup.org/documentation/v2/mediasoup/api/#server-Room).

mediasoup-client will filter all other codecs present in the browser media capabilities and generate the appropriate SDP answer with such a single codec.

In this case, you want to provide a video codec such as:

```` 
{
  kind: 'video',
  name: 'H264',
  clockRate: 90000,
  parameters:
  {
    'packetization-mode': 1,
    // 'profile-level-id'        : '42e01f', // OpenH264 encoder.
    'profile-level-id'        : '42001f', // Hardware encoder.
    'level-asymmetry-allowed' : 1
  }
}
````

**Comment by pavelserbajlo** [comment]
@jmillan: we tried that profile already, but it always uses OpenH264. Works well in Munge SDP or AppRTC, not with mediasoup. More on our experiments here: https://groups.google.com/d/msg/mediasoup/fhqx0qkFSjo/510jWxQGCAAJ

**Comment by jmillan** [comment]
please open a discussion in https://mediasoup.discourse.group/ so we can discuss there without polluting this issue.

**Comment by ibc** [comment]
Closing issue since we already handle this [libwebrtc bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=10746) in mediasoup by parsing both H264 frame marking and codec payload to detect key frames.
