### ISSUE TITLE
PlainRtpTransport has undefined tuple.localIP

### ISSUE THREAD

**Issue by j1elo** [versatica/mediasoup#330]
### Your environment

- Operating system: Ubuntu 16.04 "Xenial"
- Node version: 8.16.1
- npm version: 6.11.2
- gcc/clang version: 9.1.0
- mediasoup version: 3.2.5
- mediasoup-client version: 3.2.4

### Issue description

When a PlainRtpTransport is created, its `transport.tuple.localIP` is `undefined`:

```js
const transport = await router.createPlainRtpTransport({
  listenIp: { ip: "127.0.0.1", announcedIp: null }
});

console.log(
  "mediasoup RTP transport created: %s:%d (%s)",
  transport.tuple.localIP,
  transport.tuple.localPort,
  transport.tuple.protocol
);

// Output:
// mediasoup RTP transport created: undefined:43239 (udp)
```

This also happens with the `String` version of the `listenIp` argument:

```js
const transport = await router.createPlainRtpTransport({
  listenIp: "127.0.0.1"
});
```

**Comment by ibc** [comment]
The doc is (was) wrong. Fixed now. It's `tuple.localIp` and not `tuple.localIP`.

Thanks for reporting :)

**Comment by j1elo** [comment]
> It's `tuple.localIp` and not `tuple.localIP`.

That's the same :) I'll wait for the updated docs and see what you meant.
Thanks!

EDIT - Now I see it!! `/IP/Ip/g`

**Comment by ibc** [comment]
The doc is already fixed and deployed. It said `listenIP` instead of `listenIp`:

https://github.com/versatica/mediasoup-website/commit/84febb8bffef73eefb07bad6218eae2ecf6b3a3d

1. Do you mean that `tuple.listenIp` is also `undefined`?
1. If so, please try by not passing `announcedIp: null` and check `tuple.listenIp` (so this would be indeed a bug).

**Comment by ibc** [comment]
ah ok, so clear now :)
