### ISSUE TITLE
Direct C++ API

### ISSUE THREAD

**Issue by ambyjkl** [versatica/mediasoup#336]
## Feature Request
Rather than having to configure the server through Node.js, it would be nice to have a direct C++ API to do the same. That way users can avoid pulling in Node.js as a dependency if they don't want to.

Perhaps the first step towards this would be to pull in the npm dependencies into the C++ layer if possible. I guess in the long term, having everthing implemented in C++ would be beneficial, and Node.js's role would be diminished to merely that of a binding. I'm not sure if this is in line with the current vision of the project, since there are a lot of actual features that could be built instead, but still, I'm leaving this here as a possibility.

**Comment by ibc** [comment]
This is not gonna happen (at least in the short and medium term) as it would mean LOT of work for us. The `mediasoup/lib` folder has lot of JavaScript code that is required to make mediasoup work, manage C++ worker subprocesses, properly negotiate media codecs and RTCP, etc. The JS layer of mediasoup is much more than just an “API” to manage the C++ subprocesses.

I will close this issue since I want to not keep issues permanently opened in GitHub.

**Comment by ambyjkl** [comment]
Oh I see. I went merely by the 90.7% C++ on the repo, but 8.7% JS is indeed a lot must agree; it definitely is an incredible amount of work. This is definitely more of a stretch goal imho, maybe something for v5, but something I would definitely love see happen. Maybe if I have time to spare I can be a part of it :)
