### ISSUE TITLE
retransmitted calculate issue

### ISSUE THREAD

**Issue by MichaelShu3333** [versatica/mediasoup#401]
### Issue description
in the file of worker\src\RTC\RtpStreamSend.cpp:
in function void RtpStreamSend::UpdateScore(RTC::RTCP::ReceiverReport* report)

		if (repaired > lost)
		{
			if (HasRtx())
			{
				repaired = lost;                      <--
				retransmitted -= repaired - lost;     <--
			}
			else
			{
				lost = repaired;
			}
		}

in the case HasRtx is true, retransmitted dose not change, 
I think repaired = lost; should after retransmitted -= repaired - lost;

**Comment by ibc** [comment]
@jmillan can you check please? I'm not sure about the error.

**Comment by penguinol** [comment]
`repaired = lost;`
so `repaired - lost = 0`
It looks like a bug

**Comment by ibc** [comment]
Right. We'll fix it.

**Comment by ibc** [comment]
I see there is a noop line (`retransmitted -= 0`), it can be removed but I do not see any bug here:

```c++
if (repaired > lost)
{
	if (HasRtx())
	{
		repaired = lost;
		retransmitted -= repaired - lost;
	}
	else
	{
		lost = repaired;
	}
}
```

@jmillan, we are not modifying `retransmitted` above (since `repaired - lost === 0`). Perhaps we should we update `retransmitted` `if `repaired <= lost`?

**Comment by MichaelShu3333** [comment]
@ibc if repaired - lost === 0, maybe retransmitted < repaired?
I got this case

**Comment by ibc** [comment]
Not sure, we need to do some checks.

**Comment by jmillan** [comment]
This block of code makes me question many things. The only thing that makes sense to me is:

```cpp
if (repaired > lost)
        repaired = lost;
}
```

Of course this line is a noop: `retransmitted -= repaired - lost;`
This line is nonsense: `lost = repaired;`

On the other hand, why are we treating RTX differently, do you recall @ibc? The thing is that we store the received RTP packets for later retransmission upon NACK reception. If RTX is used we encode them before retransmitting, otherwise we don't. Then why do we do any differentiation at all?

**Comment by ibc** [comment]
> On the other hand, why are we treating RTX differently, do you recall @ibc?

Because Firefox does not support RTX so without different maths the score results were not useful.

**Comment by jmillan** [comment]
Fixed in v3.
