### ISSUE TITLE
[Rust] implement Deserialize/Serialize for some structs

### ISSUE THREAD

**Issue by gengteng** [versatica/mediasoup#653]
I think it would be better to provide the same serialization and deserialization support as in JavaScript for these structures in Rust.

* WorkerSettings
* WorkerLogLevel
* WorkerLogTag
* WorkerDtlsFiles
* WorkerUpdateSettings
* RouterOptions
* PipeTransportOptions
* PlainTransportOptions
* WebRtcTransportOptions
* DirectTransportOptions
* AudioLevelObserverOptions

**Comment by nazar-pc** [comment]
Everything that is `*Options` can't implement it (not fully) because of `AppData` field, which contains `std::any::Any` and can be anything. For others they are not supposed to be sent from anywhere external either and rather be written in the backend code explicitly, thus not requiring serialization/deserialization.

Please create a topic on the [forum](https://mediasoup.discourse.group/) with specific use cases you have in mind and we'll see what can be done about it.
