### ISSUE TITLE
Split `Worker` object creation from launching child process

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#668]
At https://github.com/versatica/mediasoup/blob/0a4ab953721b2971a749968ea145c2166b12cde7/lib/Worker.js#L63-L100 we see that `Worker` constructor is spawning the Worker child process and creating the channels for comunicating with it. It could be possible to add an option to provide already created processes or channels, so actual Worker processes could be in other machines, making it dead simple to have horizontal scaling and more performant. For that, it would only be needed to move the creation of the Worker process and the channels to an exported factory function, decoupling them from the spawing of processes in local.

**Comment by nazar-pc** [comment]
It is not as simple if you are building production-grade software. Every request over TCP/WS/whatever can hang and time out, can drop and reconnect, all kinds of things can happen that need to be accounted for and that makes the library A LOT more complex both internally and externally. I do not think this is ever going to happen to be honest.

**Comment by piranna** [comment]
Probably yes, but what I'm saying is to allow to provide as parameter of `createWorker()` your own API compatible channel instances, and if not provided, create them as is happening now. Then, the networking issues you are talking about are responsability of the developer of that channel instances, not of Mediasoup.

**Comment by ibc** [comment]
I fail to see how a mediasoup Node process running in host A can be provided with a mediasoup-worker process running in host B, plus you cannot just run mediasoup-worker process, so this feature request comes with the implicit assumption that mediasoup Node can connect to a mediasoup-worker running in a separate host via TCP (or whatever channel).

This is out of the scope of mediasoup. Horizontal scalability is supposed to be done at higher level (at app level). In addition, it's not a good idea that a single mediasoup Node process (which is also the custom process) manages tons of worker processes. At some point the single Node process may become a bottleneck. In this case, using Node Workers (different system threads) would make sense. But again, that's application business. mediasoup library is not gonna provide with these things since they can be done at app level in the preferred way.

Let's close this feature request since this is not gonna happen within mediasoup library.

**Comment by piranna** [comment]
This proposal was not explicitly about horizontal scaling, but about remote controling Workers on another mediasoup instance. So far I'm able to remote controling other mediasoup instances, that proposal would allow to do it at a lower level and improving performance by not needed to convert messages types and by-passing some hops.

On the other hand, it's true that this would potentially make a single mediasoup Node process to manage a lot of (remote) Worker processes, but this can still be done at application level too (and in fact they do, all mediasoup projects that I've seen that try to have horizontal scaling at somewhat low level, their first aproach to implement some kind of `RemoteWorker`).

**Comment by piranna** [comment]
If so, would you accept a PR implementing this, if it showed to be small and simple?

**Comment by ibc** [comment]
One of the mediasoup goals is to avoid any network signaling. By allowing custom (or built-in) TCP channels it means that mediasoup must manage them (deal with disconnections, reconnections, lost messages, etc). Plus such a feature requires that the user/app should be able tu run a mediasoup-worker process directly instead of being spawned by the mediasoup Node/Rust layer.

I'm afraid this is completely out of the scope of mediasoup and any approach that we may include would be too opinionated and would require lot of maintenance work from us. We want it to be super low level so we work less and users can decide the high level layer based on their needs, skills and creativity. We don't want to play that role.

Serializing messages via TCP between two backend servers (one of them behaving as centralized controller and others running mediasoup Node/Rust and workers) should not involve any important overhead and doesn't justify the amount of work that should be done and maintained if we implement the proposal in this feature request.
