### ISSUE TITLE
Pausing a simulcast consumer returns different values for producerScore and producerScores

### ISSUE THREAD

**Issue by hkirat** [versatica/mediasoup#676]
## Bug Report

If we pause a mediasoup simulcast consumer, anytime the `score` event is triggered on the consumer, `score.producerScore` is `0`, but `score.producerScores` contains an array of non zero values (if the user is on a good connection ofcourse). 

I'm not sure which one is a better (whether the producer Score should be zero or non zero when a consumer has been paused) but might be nice if they are consistent. 

I think this happens because when we pause a consumer, we set the spatial layer to be `-1` https://github.com/versatica/mediasoup/blob/ede3644e3418a75752ec82f1e831e231ff926951/worker/src/RTC/SimulcastConsumer.cpp#L1064 

And when a subsequent `consumerScore` event is triggered,  since the spatial layer is -1, we set `producerScore` to explicitly be `0`, but `producerScores` still returns a non-zero value. 

https://github.com/versatica/mediasoup/blob/ede3644e3418a75752ec82f1e831e231ff926951/worker/src/RTC/SimulcastConsumer.cpp#L188

I'm not sure if this is intended behaviour, and apologies in advance in case it is, or if I'm missing something obvious in my understanding of this.

### Your environment

- Operating system: MacOS
- Node version: v14.17.0
- npm version: 6.14.13
- gcc/clang version: Apple clang version 11.0.3 (clang-1103.0.32.62)
- mediasoup version: 3.8.3
- mediasoup-client version: 3.6.39

**Comment by ibc** [comment]
When you pause a Producer in mediasoup side it means that mediasoup won't forward packets to its Consumers. However when you pause a Producer in mediasoup-client side, the webrtc engine still sends RTP packets to the server (less than before and just silence audio packets or black frame video packets), that's why the score in mediasoup Producer is not zero.

Yes, when the Consumer is paused (because the Producer is paused or because just the Consumer is paused) we force producerScore to be 0 artificially. I may understand this is an artificial decision but it's like that by design. You should not care about Producer score if the Consumer is paused.
