### ISSUE TITLE
mediasoup-helpers

### ISSUE THREAD

**Issue by piranna** [versatica/mediasoup#705]
## Feature Request

Not a feature request, but more like a showcase, open discussion... or feature request :-)

As said at https://github.com/versatica/mediasoup/pull/697#issuecomment-955238546, while working on [Mafalda SFU](https://github.com/Mafalda-SFU) I've found multiple APIs that are ad-hoc helpers, sugar syntax or static descriptions, that could be moved out of Mediasoup core package, both to reduce its size and be reused elsewhere without needing to do requests to the core, and in fact I've already created some packages with them ready use/merge/whatever:

- [supported RTP capabilities](https://github.com/Mafalda-SFU/supported-RTP-capabilities): static hard coded list of capabilities supported by Mediasoup. In that package I extracted it as a Typescript object (in fact, a copy&paste of Mediasoup code) due to usage of some Mediasoup types definitions from `RtpParameters.ts` file, but can be easily a plain JSON object too, so there would not be any Mediasoup dependencies.
- [scalability modes](https://github.com/Mafalda-SFU/scalability-modes): pure function to parse spatial and temporal layers, with no dependencies at all. It's included in Mediasoup code but not used directly nor makes use of Mediasoup at all, it's just only provided as a helper function itself, so makes total sense to have it in an independent standalone package.
- [ORTC canConsume](https://github.com/Mafalda-SFU/ORTC-canConsume): helper functions to validate if some RTP capabilites can consume a Producer. The same as *supported RTP capabilities*, it doesn't make use of Mediasoup APIs except for some Typescript types definitions from `RtpParameters.ts` file, so both packages could be combined.

Last but not least, just only that I've not done a package for it yet, as already discussed `pipeToRouter()` is just syntaxtic sugar and a helper function, so it can be moved out of Mediasoup core. Currently code do some verifications to ensure desired Producer is in fact owned by sender Router, and doing so access some private properties, but except from that, moving the method out would allow to do some improvements:

- being a pure function instead of a Router method, by providing source Router as a parameter, allowing easily to reuse it
- hardest part is creation of the PipeTransports link part, specially when connecting between two different servers. That makes no usage of private APIs, and could be extracted to a new `createPipeTransportLink()` function, without needed to specify any Producer or DataProducer, just only create the link

This could also leads for some improvements, without needed to maintain them in the Mediasoup core code:

- checks for sending just only a Producer or DataProducer and not none or both is artificial. Also it could allow to send multiple of them on a single call
- use a DataChannel connection to transmit events when connecting Routers between two servers (local one can still use Node.js for performance)

All this changes can be applied right now, by using these packages as dependencies in the 3.x versions, and deprecate and remove them in a future 4.x versions, pointing users to use them directly. What I'm not so sure is about having a single `mediasoup-helpers` package that collect all of them, or have multiple specialized ones. Maybe being `mediasoup-helpers` an empty umbrella package using the other ones as dependencies? Should these packages hosted inside the Mediasoup organization, specially the ones that have actual Mediasoup code?

**Comment by ibc** [comment]
* **supported RTP capabilities** is not a helper, it's part of mediasoup core. Values in there (such as supported codecs, the `id` of RTP header extensions and supported RTCP feedbacks in each codec) are not up to the app, they are part of mediasoup and need to correlate with C++ code.

* **scalability modes** is a regex function that is also implemented in C++ so it's part of mediasoup, not up to external app. It's a function exported by mediasoup that must do exactly what it does, it doesn't make sense to move outside.

* **ORTC canConsume()** requires lot of logic in `ortc.ts` file and is needed for the app to know whether an endpoint can consume a Producer or not. This is core stuff as well.

* **pipeToRouter()** is indeed sugar API but due to its complexity and extended usage it makes sense to be part of mediasoup.

* **createPipeTransportLink()** looks indeed suitable for an external package, but it could involve also signaling (TCP, WebSocket, whatever) between servers, and we are not gonna mandate that. 

> use a DataChannel connection to transmit events when connecting Routers between two servers (local one can still use Node.js for performance)

This is exactly what I don't want to do: decide a signaling mechanism between servers.

Anyway, as I said in another discussion, I don't want to maintain a separate `mediasoup-helper` package. I don't want to decide any "good set of codecs for `createRouter()`" nor provide with opinionated APIs to connect two servers running mediasoup.

I'd appreciate if those topics could be discussed in the forum. We try to keep GH open issues/features as reduced as possible. I understand this is a legitimate feature request though. I'll close this feature request because it goes in the path that I want to avoid (and it just means more and more work for us).
