### ISSUE TITLE
Memory leak in mediasoup c++ worker 

### ISSUE THREAD

**Issue by itzmanish** [versatica/mediasoup#769]
### Your environment

- Operating system: Debian
- Node version: v16.14.0
- npm version: 8.3.1
- gcc/clang version: gcc (Debian 10.2.1-6) 10.2.1 20210110
- mediasoup version: v3.9.3
- mediasoup-client version: 

### Issue description
C++ worker doesn't free memory once all participant left and router is closed with `router.close`.

So I create one router on one worker on one cpu, then create meeting with some participant(~30-40) I see ram usages go up to ~600 MBs then all participant left and router got closed. but I can see that mediasoup worker is still taking the same amount of memory.

This heavily affects big meetings happening on routers. I have also opened a discussion on [forum](https://mediasoup.discourse.group/t/mediasoup-has-memory-leak-in-v3-9-3/3947).
![2022-02-16_17-02](https://user-images.githubusercontent.com/12438068/154265777-b2f132f1-239d-4e45-a7dd-77551e17b6a5.png)

**Comment by jmillan** [comment]
This is probably related to the leak I'm seeing in v3. So I'm going to reuse this issue.

**STR**:

* start mediasoup-demo locally
* open the browser and join a specific meet with many tabs
* monitor the `mediasoup-worker` memory usage
* wait some time (few seconds, or a minute)
* close tabs 

## What happens?

mediasoup-worker memory is not released

## What should happen?

memory should be released

## Notes

After some investigations I came to the fact that initialising `buffer` [here](https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/RtpStreamSend.cpp#L39) with a much larger size (262144 instead of 65536) makes the memory to be released.

I'm still investigating this issue. I've verified that each cloned RTP packet is deleted, so the leak is not that.

@ibc, any idea?

**Comment by penguinol** [comment]
I've also found memory leak problem in my branch, not sure whether it's the same as v3 branch.
Asan says nothing，so it may not caused by missing of delete/free.
Still trying to find the reason.

**Comment by penguinol** [comment]
Here is some progress:
I found the memory will keeping increase when worker is under heavy load, such as calling 500 terminal in one server with 1000M eth bandwidth, 50 terminals per worker.
I used gperftools to watch the increment of  memory, and it shows most of memory was applyed by UvSendData
![pic](https://user-images.githubusercontent.com/14129614/156099434-8d2c0f67-82c8-404d-aee1-74d586f5e54b.png)
So i added a counter in UvSendData as follow
```cpp
struct UvSendData
	{
		explicit UvSendData(size_t storeSize)
		{
			this->store = new uint8_t[storeSize];
			this->storeSize = storeSize;
			++totalNumber;
			++leftNumber;
			totalSize += storeSize;
			leftSize += storeSize;
		}

		// Disable copy constructor because of the dynamically allocated data (store).
		UvSendData(const UvSendData&) = delete;

		~UvSendData()
		{
			delete[] this->store;
			delete this->cb;
			--leftNumber;
			leftSize -= this->storeSize;
		}

		static uint64_t totalNumber;
		static uint64_t leftNumber;
		static uint64_t totalSize;
		static uint64_t leftSize;
		size_t storeSize{ 0 };
		uv_udp_send_t req;
		uint8_t* store{ nullptr };
		UdpSocketHandler::onSendCallback* cb{ nullptr };
	};
```
And it shows the left number of uvSendData will keeping increase under this situation.
`"uvDataLeftNum": 246449, "uvDataLeftSize": 83873064, "uvDataTotalNum": 7701001, "uvDataTotalSize": 2638616809`
So here is the first problem: when outgoing streams need more bandwidth than netcard has, the packets will pile up.

Then i released all conference, and it show all the UvSendData has been destoryed.
`"uvDataLeftNum": 0, "uvDataLeftSize": 0, "uvDataTotalNum": 8230162, "uvDataTotalSize": 2818795277`
But the memory usage of worker did not decrease.
I'm not quite sure why, i guess it's beacuse of memory fragmentation, we may apply too mush small memory.

Maybe #675 can help.

**Comment by penguinol** [comment]
I called `malloc_trim(0)` manually after released all conferences, and the memory was given back to the system.
before trim:
`root      404394 34.9  4.0 2655284 2632912 ?     Ssl  13:23  20:08`
after trim:
`root      404394 34.5  0.0 2655156 23004 ?       Ssl  13:23  20:08`

For the first problem, we may add a limitation to the packets queue, if there is too many waiting packets, we just drop the newer one.

**Comment by jmillan** [comment]
@penguinol,

This is somehow expected. I'm also experiencing this with `RtpStreamSend`.  The fact that the system does not `see` that the memory has been released from mediasoup does not mean that it is in use, and hence that there is a memory leak. `malloc` will keep the memory previously requested and already freed accessible for the process in order to avoid the more expensive operations of returning it to the system, and requesting later for more.

As you proved, calling `malloc_trim(0)` does show that the memory is indeed free. Accesible to the process.


Now, such memory should be accessible for future use for mediasoup worker. If instead of that it keeps growing when you start another router with less traffic later this must be further checked.

**Comment by jmillan** [comment]
And that is why valgrind and friends won't see in this case any memory leak.

**Comment by jmillan** [comment]
In `RtpStreamSend` there is the following problem when creating many `Consumers` at the same time:

The creation of the `RtpStreamSend` instance initialises a vector of 65536 positions and another of 600, for video steams. Whenever the corresponding `Router` ends up, the memory is seen by the OS as in use, but it is not (I've verified this using `malloc_zone_pressure_relief` in MacOS).

The problem in this case is that for future `Routers`, the memory will keep growing. This is, the vector requires adjacent memory and it seems that it does not find it in the already released one, so it requests the OS for more, which could end up in an out of memory condition.

If I allocate four times more positions in the vector (262144) the memory is seen by the OS as free as soon as the `RtpStreamSend` is destructed. This is because `malloc` will do it (release the freed memory to the system) for big memory chunks.

On option is, thus, releasing the free memory upon `Router` destruction.

**Comment by ibc** [comment]
> This is, the vector requires adjacent memory

How can this be an issue in C++?

**Comment by jmillan** [comment]
> How can this be an issue in C++?

`std::vector` tells `malloc` that it needs a block of X bytes. Malloc does not have such a big free block at the moment, it may have a X-Y bytes one though, so it request yet another X bytes block to the OS.

**Comment by ibc** [comment]
But I fail to understand how it can produce a real leak if we are using C++ `std::vector` correctly. I mean, I understand it could be less efficient and take longer to release memory, but I cannot understand that a proper usage of C++ `std::vector` produces a real and non solvable leak.

**Comment by jmillan** [comment]
> But I fail to understand how it can produce a real leak if we are using C++ std::vector correctly. I mean, I understand it could be less efficient and take longer to release memory, but I cannot understand that a proper usage of C++ std::vector produces a real and non solvable leak.

If C++ requests a block of X bytes via `malloc` and this does not have such a pristine previously freed block available at the moment, it will request the OS another one.

So we may be in a situation where `mediasoup-worker` has a lot of memory, most of it free, but there is no a free block of X bytes, and keep requesting the OS until we get out of memory.

**Comment by jmillan** [comment]
On this regard I'm testing `memory-optimizations` approach to see if the issue is prevented there.

**Comment by penguinol** [comment]
> In `RtpStreamSend` there is the following problem when creating many `Consumers` at the same time:
> 
> The creation of the `RtpStreamSend` instance initialises a vector of 65536 positions and another of 600, for video steams. Whenever the corresponding `Router` ends up, the memory is seen by the OS as in use, but it is not (I've verified this using `malloc_zone_pressure_relief` in MacOS).
> 
> The problem in this case is that for future `Routers`, the memory will keep growing. This is, the vector requires adjacent memory and it seems that it does not find it in the already released one, so it requests the OS for more, which could end up in an out of memory condition.
> 
> If I allocate four times more positions in the vector (262144) the memory is seen by the OS as free as soon as the `RtpStreamSend` is destructed. This is because `malloc` will do it (release the freed memory to the system) for big memory chunks.
> 
> On option is, thus, releasing the free memory upon `Router` destruction.

I commeted code from after this line, and ran heap profile again. https://github.com/versatica/mediasoup/blob/ff17d135957513aff86d45d99e82ffce45187318/worker/src/handles/UdpSocketHandler.cpp#L189

It shows RtpStreamSend objects cost most of memory now.

> Total: 461.8 MB
   387.3  83.9%  83.9%    387.3  83.9% RTC::RtpStreamSend::RtpStreamSend
    30.3   6.6%  90.4%     30.3   6.6% std::_Rb_tree::_M_emplace_unique
    23.2   5.0%  95.5%     42.2   9.1% RTC::RtpPacket::Clone
    19.0   4.1%  99.6%     19.0   4.1% std::_Rb_tree::_M_emplace_hint_unique [clone .isra.0]
     0.5   0.1%  99.7%      0.5   0.1% RTC::RateCalculator::GetRate
     0.4   0.1%  99.8%      0.4   0.1% RTC::RateCalculator::Update
     0.4   0.1%  99.8%      0.4   0.1% std::vector::reserve

When we `malloc` a memory < 128K, glibc will call `brk()/sbrk()` to alloc memory from sytem, when we `malloc` a memory >128K, glibc will call `mmap()` to alloc memory.
Memory alloced by `mmap()` will be release back to the system once we free it. Memory alloced by `brk()` will only be release back to the system when there is a contiguous 128K  memory on the top of  heap.
 
See M_TRIM_THRESHOLD and  M_MMAP_THRESHOLD in https://man7.org/linux/man-pages/man3/mallopt.3.html
That's maybe why the memory of a four times size vector will be release as soon as it destructed.

So i think we should make the size of UvDataSend a fixed value to avoid holes in heap, and use memory pool or circular queue, so that glibc can use `mmap` to alloc memory, and limit the max number of UvDataSend objects to avoid out of memory in heavy load.

**Comment by jmillan** [comment]
> See M_TRIM_THRESHOLD and M_MMAP_THRESHOLD in https://man7.org/linux/man-pages/man3/mallopt.3.html

Correct. Could you try modifying those values to make the memory be released given the current `RtpStreamSend` vector sizes?

NOTE:
* That is only available in linux
* You can simply set the corresponding env variables to the desired values when running `mediasoup-worker`

**Comment by prlanzarin** [comment]
> Thanks for the hints, @Hartigan, there was incorrect handling for timestamps when they wrap around. Latest commit should resolve this. I was able to reproduce the issue with videoroom example app and after fixes memory doesn't seem to leak anymore as far as I can tell.
> 
> As a sidenote I was also surprised that timestamps on consumers start with 1 instead of random number, makes testing slower that would have been otherwise.
> 
> cc @prlanzarin

@nazar-pc 

Sorry for the late reply.

I'll re-run the load tests (same as the ones I mentioned in the discourse thread) against the tip of memory-optimizations branch and compare it against the latest v3 commit.
I'll also put memory-optimizations running again in a test server with real users compared against v3.9.8. I can get the results to both published either here or in the discourse thread (I'm thinking the latter).

**Comment by jmillan** [comment]
> So i think we should make the size of UvDataSend a fixed value to avoid holes in heap, and use memory pool or circular queue, so that glibc can use mmap to alloc memory, and limit the max number of UvDataSend objects to avoid out of memory in heavy load.

There are different things happening here:
* We could use a memory pool as within other instances in `memory-optimization` branch (WIP)
  * This implementation does allocate (malloc) memory if there is no memory from a previously created instance or reuse it otherwise.
  * That would not prevent holes in the heap unless we preallocate contiguous memory for each pool.

**Comment by jmillan** [comment]
> See M_TRIM_THRESHOLD and M_MMAP_THRESHOLD in https://man7.org/linux/man-pages/man3/mallopt.3.html
That's maybe why the memory of a four times size vector will be release as soon as it destructed.

In any case, playing with these env variables should help releasing memory to the system and avoiding this holes in heap.

**Comment by jmillan** [comment]
Hi @penguinol, did you have the chance to play with M_TRIM_THRESHOLD and M_MMAP_THRESHOLD?

**Comment by penguinol** [comment]
> Hi @penguinol, did you have the chance to play with M_TRIM_THRESHOLD and M_MMAP_THRESHOLD?

I'll try this next week.

**Comment by jmillan** [comment]
> I'll try this next week.

Fantastic, I'll look into it too.

**Comment by jmillan** [comment]
We are going to add an API to be able to explicitly release memory via `malloc_trim()` in linux and the analogous in osx. cc @penguinol

**Comment by penguinol** [comment]
I tested mediasoup with `MALLOC_MMAP_THRESHOLD_=65536`.
When about 50 peers in one worker, it cost about 500-600MB memory.
After I released the conf, the memory usage was about 100MB.
Did the same test without setting `MALLOC_MMAP_THRESHOLD_`, memory usage was still 500-600MB after released the conf.
The inital memory of mediasoup is about 10MB.
So setting a smaller `MALLOC_MMAP_THRESHOLD_` may help to relase most of memory to system.

**Comment by ibc** [comment]
> MALLOC_MMAP_THRESHOLD_

I assume this is a C macro so it must be defined on worker build time, so we need to decide a fixed value for this limit that should be good for all scenarios. How can we decide it? A higher value means more memory usage and more efficient runtime, while a lower value means the opposite.

**Comment by jmillan** [comment]
> I assume this is a C macro so it must be defined on worker build time, so

No, it's an env variable.

I'm testing this in Docker and I'm not getting those results.., memory is not being released with `MALLOC_MMAP_THRESHOLD_=65536`

**Comment by jmillan** [comment]
> I'm testing this in Docker and I'm not getting those results.

Retesting..

**Comment by penguinol** [comment]
I also tested [tcmalloc](https://gperftools.github.io/gperftools/tcmalloc.html) and [jemalloc](http://jemalloc.net/) by setting `LD_PRELOAD`.
tcmalloc performed as same as glibc malloc.
jemalloc performed quite good, the memory usage dropped to 30MB after released the conf.
Maybe jemalloc is a better choice.

**Comment by jmillan** [comment]
I'm not seeing consistent results with `MALLOC_MMAP_THRESHOLD_`. I've used 65536 and 32768 values. It sometimes reduces the memory considerably but other times doesn't.

**Comment by jmillan** [comment]
Good points @penguinol, I'm going to test `jemalloc`

**Comment by jmillan** [comment]
Indeed `jemalloc` does have a very good result in my tests too. Avoiding fragmentation and releasing the memory when the activity ceases.

There are quite some important figures using it indeed https://github.com/jemalloc/jemalloc/wiki/Background#adoption

And a good thing is that there is no need to touch `mediasoup`. As the only thing we do is tell the binary to use it via LD_PRELOAD env variable.

**Comment by nazar-pc** [comment]
Hm, there is always a tradeoff between how efficient things are and how much memory is used. A long as it is not leaking, I don't think we need to do anything. Just preload custom allocator or configure default allocator if it matters too much.

We might need to be more clear in documentation that it doesn't make sense to create a pool of workers and keep them running for a long time, instead one can create as many workers as they need on demand, thus releasing memory if no longer in use.

**Comment by ibc** [comment]
> We might need to be more clear in documentation that it doesn't make sense to create a pool of workers and keep them running for a long time, instead one can create as many workers as they need on demand, thus releasing memory if no longer in use.

For me telling that sounds like "we leak so please restart from time to time". I think we should use the most convenient allocator by default and let the user choose another if there is an easy way to do it (for instance jemalloc just requires a environment variable). And of course document that.

**Comment by nazar-pc** [comment]
There are tricks with non-default allocators. Yes, it may use less memory, but it may also increase CPU usage or increase latency at the same time. Default system allocator is a pretty safe choice from my experience.

**Comment by ibc** [comment]
Problem is that default malloc makes mediasoup leak (at least in v3 branch) by design.

BTW I'm not against using default system allocator by default.

**Comment by nazar-pc** [comment]
I don't think it leaks forever. If memory is fragmented, at some point it should stop leaking anyway, it just may use a bit more memory that would be required otherwise, but that is about it.

**Comment by ibc** [comment]
Sure thing, but it consumes a lot of memory before it releases. We are having this exact issue in production.

**Comment by nazar-pc** [comment]
Maybe it is less of an issue with memory optimizations branch?

**Comment by penguinol** [comment]
> Hm, there is always a tradeoff between how efficient things are and how much memory is used. A long as it is not leaking, I don't think we need to do anything. Just preload custom allocator or configure default allocator if it matters too much.
> 
> We might need to be more clear in documentation that it doesn't make sense to create a pool of workers and keep them running for a long time, instead one can create as many workers as they need on demand, thus releasing memory if no longer in use.

I agree with that. In fact we do not really care about cached memory. Usually we will calculate and reserve memory for mediasoup.
What we should worry about is whether cached memory can be reused and whether memory is keeping increasing over time.
In our 500 terminals per server load test, memory was keeping increasing and takes more then 10G memory beacuse packets can not be sent in time.
It's a risk, but can be avoid. Usually if we need 500 terminals in one server, we will use fiber or bonding.

**Comment by nazar-pc** [comment]
@penguinol I'm wondering if you already tried recent iteration of #675. I believe we fixed all known issues and memory usage is very promising with it. Give it a try, the usage profile will be different (it will not release some of the memory, like not even giving it back to allocator) and as far as I know doesn't contain memory leaks.

**Comment by penguinol** [comment]
> @penguinol I'm wondering if you already tried recent iteration of #675. I believe we fixed all known issues and memory usage is very promising with it. Give it a try, the usage profile will be different (it will not release some of the memory, like not even giving it back to allocator) and as far as I know doesn't contain memory leaks.

No, our branch is based on 3.8.x, there is a lot of work to do to merge to 3.9.x.

**Comment by penguinol** [comment]
I noticed you've add a limit on packet send buffer. It can avoid unlimited increasing of memory.

**Comment by jmillan** [comment]
@nazar-pc,`memory-optimizations` branch do also consume memory increasingly. It consumes less than v3 but the consumption is incremental. The memory requested to the system is not released, and new traffic, after a previous activity,  makes the allocator request more memory to the system since the currently allocated memory cannot satisfy the required sizes due to fragmentation.

We are going to keep testing `jemalloc`, which is probing to be more memory efficient, and compare. One can decide which allocator to use within a binary.

`memory-optimizations` branch is a great initiative which I'm willing to see in v3 soon. And it's a starting point for other promising optimizations. Both are different efforts that complement each other.

**Comment by CosmosisT** [comment]
When I broadcast the worker will increase to 3.3MB in my case as pipetransport and re-producing occurs/etc.
If I close the broadcast this 3.3MB won't clear but stay; if I broadcast again this 3.3MB won't increase until I add another broadcast making it two!

So not sure why it's reserving for the future...

**Comment by nazar-pc** [comment]
@CosmosisT allocators are now allocating and de-allocating memory all the time for efficiency purposes, I'm not surprised by that behavior at all, actually makes perfect sense to do what it does.

**Comment by ibc** [comment]
Closing because there is no real leak in the code and this is being handled in a separate PR.
