### ISSUE TITLE
[Rust] Impl from `Uuid` for ProducerId, TransportId....

### ISSUE THREAD

**Issue by RemiKalbe** [versatica/mediasoup#770]
## Feature Request
It's possible to convert a `TransportId`, `ProducerId`.... into a `Uuid`, but the reverse is not possible. Could it be implemented?

## Why ?
I'm using [paperclip](https://github.com/paperclip-rs/paperclip) which is a library to generate OpenAPI spec from code, they support UUID, but not TransportId... because it's not a standard OpenApi type, I could open a PR on their side but I don't think it's a great idea to open a PR for each non-standard type I need, I believe it makes more sense to be able to convert those "proprietary" types into types that any library can understand.

**Comment by nazar-pc** [comment]
It was already discussed on the forum. Distinction is made intentionally so you can't specify `TransportId` instead of `ConsumerId` and so on. It is expected that you'll either get those data structures directly from the library or via API where it'll be de-serialized with serde, thus avoiding the need to convert arbitrary `Uuid` which may not represent a real `TransportId`.

I'm a bit reluctant to support turning arbitrary `Uuid` into `*Id`.

**Comment by RemiKalbe** [comment]
It went complety over my head that I could simply use a `serde_json::Value`, and then parse it in my code. Sorry about that.
