### ISSUE TITLE
Remove Return Types where possible?

### ISSUE THREAD

**Issue by mango-martin** [versatica/mediasoup#951]
I saw movement in my open PR #869 and want to re-do it with a bit more thought put into it.

Anyway, this is unrelated, while going through the code I noticed that every single getter and function has a return type attached to it.

I think that all of these can be removed (with some exceptions). TypeScript inference is powerful. It will know the type of the returned "thing". There are a few cases where it makes sense to "override" inference, for example you would like to throw an error in a function that is designed to returned a specific value:
```
function add(a: number, b: number) : number {
  if (typeof a !== 'number' || typeof b !== 'number') throw new Error('Only numbers allowed');
  return a + b;
}
```
If you'd use that exact function statement without the return type, TS would raise the Error `result is possibly undefined` because in the error case it doesn't actually return anything.

But for most cases, return statements are unnecessary - and as an added benefit, can even inform you of an unhandled edge case.

This is a minor thing in the great scheme of things, but I think it would help maintainability of the library and testing to remove all return types for all cases that are unlike the one mentioned above - at least for all getters of fields that are already typed.

Working on the "Generic AppData" I noticed that the actual change is not that hard to implement, but with existing structure there are hundreds of lines of code that would need to be changed - and this might apply to any other TypeScript related changes in the future.

**Comment by ibc** [comment]
> I saw movement in my open PR #869 and want to re-do it with a bit more thought put into it.

If you are gonna create a new PR please close the former.

Regarding return type in getters, we prefer to be strict and declare it. I know it's not required but in some cases, such as in mediasoup-client, we declare class interfaces with getters and here we just clearly define the return type of those getters (since - method or getter in an interface doesn't return anything). Anyway, no matter what, we prefer to be strict and declare return types even in getters.

NOTE: We are trying to close issues and PRs in GitHub so will close this one as well (don't want to keep discussions here). For further discussions please open a topic in the forum.

Thanks a lot.

**Comment by mango-martin** [comment]
> If you are gonna create a new PR please close the former.

Will do, as soon as I have the new one ready.

> NOTE: We are trying to close issues and PRs in GitHub so will close this one as well (don't want to keep discussions here). For further discussions please open a topic in the forum.

👍 

About the rest: I just wanted to put it in as a suggestion. Seeing that you have reasons to keep status quo is good enough for me.

**Comment by nazar-pc** [comment]
> I think that all of these can be removed (with some exceptions). TypeScript inference is powerful. It will know the type of the returned "thing".

You should ALWAYS specify input and output types, so both compiler and you (developer/maintainer/etc.) don't need to guess what type is every time. Also internal types may change during refactoring and it is nice to get compilation error about type mismatch rather than silently changing return type.
